name = "simple-r2-form"
main = "src/worker.ts"
compatibility_date = "2023-08-12"

workers_dev = false

# add a route here or in the dashboard

[vars]
PUBLIC_BUCKET_URL="https://i.sportshead.dev"

[[r2_buckets]]
binding = "R2"
preview_bucket_name = "images"
bucket_name = "images"

